services:
  frontend:
    build:
      context: ./frontend
    container_name: silvert-frontend
    restart: unless-stopped
    expose:
      - "80"

  nginx:
    depends_on:
      - telegram-bot
      - frontend
    volumes:
      - ./nginx/default.with-frontend.conf:/etc/nginx/conf.d/default.conf:ro
